# Generated by Django 3.0.3 on 2020-03-13 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_title', models.CharField(choices=[('Profile', 'Profile'), ('Activity', 'Activity'), ('Project', 'Project')], default='Profile', max_length=30)),
                ('index_title', models.CharField(choices=[('Profile', (('Skill', 'Skill'),)), ('Activity', (('UCI Undergraduate Researcher', 'UCI Undergraduate Researcher'), ('Coding HelpDesk', 'Coding HelpDesk'), ('Heronation InternShip', 'Heronation InternShip'))), ('Project', (('Face Recogntion', 'Face Recognition'), ('Mu:Ping App', 'Mu:Ping App'), ('Ang-Bob App', 'Ang-Bob App'), ('Flex-Bison Interpreter', 'Flex-Bison Interpreter'), ('Z-shop App', 'Z-shop App')))], default='Skill', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_title', models.CharField(choices=[('Profile', 'Profile'), ('Activity', 'Activity'), ('Project', 'Project')], default='Profile', max_length=30)),
                ('index_title', models.CharField(choices=[('Profile', (('Skill', 'Skill'),)), ('Activity', (('UCI Undergraduate Researcher', 'UCI Undergraduate Researcher'), ('Coding HelpDesk', 'Coding HelpDesk'), ('Heronation InternShip', 'Heronation InternShip'))), ('Project', (('Face Recogntion', 'Face Recognition'), ('Mu:Ping App', 'Mu:Ping App'), ('Ang-Bob App', 'Ang-Bob App'), ('Flex-Bison Interpreter', 'Flex-Bison Interpreter'), ('Z-shop App', 'Z-shop App')))], default='Skill', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
