# Generated by Django 3.0.3 on 2020-03-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200313_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='groupno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
    ]
