# Generated by Django 3.0.3 on 2020-02-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index_title',
            field=models.CharField(default='index', max_length=200),
            preserve_default=False,
        ),
    ]
