# Generated by Django 3.0.3 on 2020-02-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_index_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_title',
            field=models.CharField(choices=[('Profile', 'Profile'), ('Activity', 'Activity'), ('Project', 'Project')], default='Profile', max_length=10),
        ),
    ]
