# Generated by Django 3.0.3 on 2020-02-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_parent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index_title',
            field=models.CharField(choices=[('Skill', 'Skill'), ('UCI Undergraduate Researcher', 'UCI Undergraduate Researcher'), ('Coding HelpDesk', 'Coding HelpDesk'), ('Heronation InternShip', 'Heronation InternShip'), ('Face Recogntion', 'Face Recognition'), ('Mu:Ping App', 'Mu:Ping App'), ('Ang-Bob App', 'Ang-Bob App'), ('Flex-Bison Interpreter', 'Flex-Bison Interpreter'), ('Z-shop App', 'Z-shop App')], default='Skill', max_length=40),
        ),
    ]
