# Generated by Django 3.0.3 on 2020-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200220_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index_title',
            field=models.CharField(max_length=200),
        ),
    ]
