# Generated by Django 3.0.3 on 2020-02-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_title', models.CharField(choices=[('Profile', 'Profile'), ('Activity', 'Activity'), ('Project', 'Project')], default='Profile', max_length=30)),
                ('index_title', models.CharField(choices=[('Profile', (('Skill', 'Skill'),)), ('Activity', (('UCI Undergraduate Researcher', 'UCI Undergraduate Researcher'), ('Coding HelpDesk', 'Coding HelpDesk'), ('Heronation InternShip', 'Heronation InternShip'))), ('Project', (('Face Recogntion', 'Face Recognition'), ('Mu:Ping App', 'Mu:Ping App'), ('Ang-Bob App', 'Ang-Bob App'), ('Flex-Bison Interpreter', 'Flex-Bison Interpreter'), ('Z-shop App', 'Z-shop App')))], default='Skill', max_length=30)),
            ],
        ),
    ]
