# Generated by Django 3.0.3 on 2020-02-27 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
