# Generated by Django 3.0.3 on 2020-02-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_menu_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_date',
        ),
    ]
