# Generated by Django 3.0.3 on 2020-02-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Menu'),
        ),
    ]
