# Generated by Django 3.0.3 on 2020-02-28 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200228_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Menu'),
        ),
    ]
