# Generated by Django 3.0.3 on 2020-02-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200228_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='groupno',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='orderno',
        ),
    ]
