# Generated by Django 3.0.3 on 2020-02-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200228_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='groupno',
        ),
    ]
