# Generated by Django 3.0.3 on 2020-03-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_mpttcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='groupno',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='orderno',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Comment'),
        ),
        migrations.DeleteModel(
            name='MPTTComment',
        ),
    ]
